title: "@sonph"
description: "Son A. Pham's personal website."
baseurl: ""

# Site url must not end with a /
url: "http://sonpham.me"

markdown: kramdown
permalink: /:categories/:title
author: sonph
gems:
  - jekyll-sitemap
  - jekyll-feed
logo: "favicon.png"

# Images dir relative to the site url.
images_dir: "assets/images"
